"""Helo

Revision ID: 268e8f08499e
Revises: 
Create Date: 2020-05-02 12:20:36.084330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268e8f08499e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('pitch', sa.String(length=255), nullable=True))
    op.drop_column('info', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('info', 'pitch')
    # ### end Alembic commands ###
